version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        environment:
            TZ: "Europe/Stockholm"
            ServerIP: "192.168.1.2"
            DNS1: "213.80.101.3"
            DNS2: "213.80.98.2"
        volumes:
            - "/data/pi-hole/etc/:/etc/pihole/"
            - "/data/pi-hole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
        dns:
            - 127.0.0.1
            - 1.1.1.1
        # Recommended but not required (DHCP needs NET_ADMIN)
        #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
