version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /docker/plex/config:/config
      - /mnt/factory/media/tv:/tv
      - /mnt/factory/media/movies:/movies
      - /mnt/factory/media/extras:/extras
    restart: unless-stopped
