version: "2"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Stockholm
      - UMASK_SET=<022>
    volumes:
      - /syncthing/config:/config
      - /mnt/factory:/factory
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
